#include <disccord/models/$$__FILE__:gsub("%.lua$", ".hpp")$$>

/*
NOTE: this code is generated by a tool (generate_models.lua)
Please make changes in $$__FILE__$$ to update this file.
*/

namespace disccord
{
namespace models
{
%s
}
}
